apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo-server
  name: echo-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: echo-server
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - image: bohanon/echo-server:latest
        imagePullPolicy: Always
        name: echo-server
        ports:
        - containerPort: 9999
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: default
  labels:
    service: echo-server
spec:
  ports:
  - name: http
    port: 9999
    protocol: TCP
  selector:
    app: echo-server
